on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: RytOuGWp469JWRhBN4Nq8YKH-76t4CT3xUei1Y9D

      - name: 📦 Install dependencies
        working-directory: ./Actions
        run: yarn install

      - name: 🚀 Build app for Android
        working-directory: ./Actions
        run: eas build -e preview -p android --non-interactive
